--------------------------------------------------------------------------------
-- copper_golem  --  a self-contained Copper Golem for Mineclonia
--------------------------------------------------------------------------------
--
-- WHAT THIS MOD DOES
--   * Adds a "Copper Golem" entity, built the Minecraft way: place a carved
--     pumpkin on top of a copper block and the two nodes turn into a golem.
--   * The golem oxidises through four IRREVERSIBLE stages over time
--     (normal -> exposed -> weathered -> oxidized), each with its own
--     body + eyes texture pair.
--   * The golem sorts nearby chests: it carries items out of the "wrong" chest
--     into the chest that already holds the most of that kind, gathering like
--     with like (each item type ends up congregating in one chest).
--
-- DESIGN NOTES (read before editing)
--   * ZERO third-party dependencies. Only stable core API is used:
--     register_entity, on_step, the node-meta inventory API, core.add_entity,
--     core.override_item, core.get_node. No mob framework, nothing experimental.
--   * The file is split into labelled sections. The two things most likely to
--     be swapped are kept apart on purpose:
--         (A) MODEL / VISUALS  -- how the golem looks per oxidation stage
--         (B) BEHAVIOUR        -- oxidation timing + chest sorting
--     You can rewrite either without touching the other; they only meet inside
--     the thin entity definition near the bottom.
--   * Oxidation is time-based and one-way, matching Minecraft. Waxing (honeycomb
--     right-click) halts it -- implemented because it was trivial here.
--
-- Mineclonia node names were verified against this install before writing:
--     copper block : mcl_copper:block[ _exposed | _weathered | _oxidized ]
--     carved pumpkin: mcl_farming:pumpkin_face
--     honeycomb     : mcl_honey:honeycomb
--     chest inv     : core.get_inventory({type="node", pos=p}) -> list "main"
--------------------------------------------------------------------------------

copper_golem = {}

--------------------------------------------------------------------------------
-- 0. CONFIG  --  tweak these; everything else reads from here
--------------------------------------------------------------------------------

local config = {
	-- Real-time seconds the golem spends in each oxidation stage before
	-- advancing to the next. Minecraft randomises this over a long period;
	-- a fixed interval is simpler and just as maintainable. Stage 4 (oxidized)
	-- is terminal. Lower this while testing if you want to watch it change.
	seconds_per_stage = 1200, -- 20 minutes per step

	-- Chest sorter. The golem gathers like items together: it finds a stack
	-- sitting in the "wrong" chest within chest_radius, carries it to the chest
	-- that already holds the most of that item, and deposits it there.
	chest_radius      = 8,    -- nodes, sort radius (source + destination must both fit)
	organize_cooldown = 12,   -- seconds between sort trips
	seek_timeout      = 12,   -- give up walking to a chest after this long
	chest_dwell       = 0.6,  -- seconds spent at an open chest (lets the lid animation show)

	-- Wandering (self-contained AI; no mob framework).
	walk_speed        = 1.4,  -- nodes/sec while strolling
	seek_speed        = 2.0,  -- nodes/sec when heading to a chest
	walk_time_min     = 1.5,  -- seconds of a walk burst
	walk_time_max     = 3.5,
	idle_time_min     = 1.0,  -- seconds of standing still
	idle_time_max     = 3.0,
}

--------------------------------------------------------------------------------
-- (A) MODEL / VISUALS  --  self-contained; no behaviour logic here
--------------------------------------------------------------------------------
--
-- Four oxidation stages, indexed 1..4. Each provides a body texture and an eyes
-- overlay, combined in-engine with the "body^eyes" texture modifier.
--
-- The mesh is models/copper_golem.b3d, GENERATED by tools/make_model.py from
-- the texture atlas itself: the 64x64 PNGs are Minecraft-style entity unwraps
-- (head 8x5x10, nose, antenna, body 8x6x6, two long arms, two legs), and the
-- script derives each box and its UV rect from that layout, then adds bones
-- and a walk animation. If you ever change the atlas layout, edit PARTS in
-- tools/make_model.py and re-run it -- don't hand-edit the .b3d.

local MODEL = "copper_golem.b3d"

-- Animation frame ranges baked into the generated model.
local ANIM = {
	stand = { x = 1,  y = 1  },  -- rest frame (frame 1 = phase 0.0); B3D is 1-indexed
	walk  = { x = 1,  y = 21 },  -- 20-frame swing cycle
	look  = { x = 31, y = 91 },  -- idle head turn L->R->L (nose/antenna ride along)
}
local ANIM_SPEED = 24 -- frames/sec the model was authored at

local STAGES = {
	{ name = "normal",    body = "copper_golem.png",           eyes = "copper_golem_eyes.png"           },
	{ name = "exposed",   body = "exposed_copper_golem.png",   eyes = "exposed_copper_golem_eyes.png"   },
	{ name = "weathered", body = "weathered_copper_golem.png", eyes = "weathered_copper_golem_eyes.png" },
	{ name = "oxidized",  body = "oxidized_copper_golem.png",  eyes = "oxidized_copper_golem_eyes.png"  },
}

local NUM_STAGES = #STAGES

-- The generated mesh has a single material slot: the full atlas.
local function mesh_textures(stage)
	local s = STAGES[stage]
	return { s.body .. "^" .. s.eyes }
end

-- The static (stage-independent) visual properties of the entity.
-- The model is authored at 1 px = 1/16 node: body 1.0 node tall, antenna tip
-- at ~1.44. Its origin is at the feet, so boxes rise from y=0.
local function base_visual_properties()
	return {
		visual               = "mesh",
		mesh                 = MODEL,
		visual_size          = { x = 1, y = 1, z = 1 },
		collisionbox         = { -0.3, 0.0, -0.3, 0.3, 1.0, 0.3 },
		selectionbox         = { -0.3, 0.0, -0.3, 0.3, 1.45, 0.3 },
		physical             = true,
		collide_with_objects = false,
		stepheight           = 1.05, -- climb a full 1-block step (like an iron golem)
		backface_culling     = false,
		hp_max               = 49,            -- 7 diamond-sword hits (sword = 7 dmg each);
		                                      -- other weapons scale by their own damage
		armor_groups         = { fleshy = 100 }, -- takes full melee damage
	}
end

-- Push the textures for `stage` onto a live object.
local function apply_stage_visuals(object, stage)
	object:set_properties({ textures = mesh_textures(stage) })
end

--------------------------------------------------------------------------------
-- (B) BEHAVIOUR  --  oxidation timing + chest sorting
--------------------------------------------------------------------------------

----------------------------------------
-- B1. Oxidation (time-based, irreversible)
----------------------------------------
--
-- Given the golem's accumulated age in seconds, return which stage it should be
-- in. Monotonic and clamped to the terminal stage, so it can never go backwards.
local function stage_for_age(age_seconds)
	local stage = math.floor(age_seconds / config.seconds_per_stage) + 1
	if stage < 1 then stage = 1 end
	if stage > NUM_STAGES then stage = NUM_STAGES end
	return stage
end

----------------------------------------
-- B2. Chest sorting (gather like items together)
----------------------------------------
--
-- Uses only the core node-meta inventory API. No chest-mod accessor needed:
-- Mineclonia chests are plain meta inventories with a list named "main".

-- Is this node one of Mineclonia's chests (single, double halves, trapped)?
-- We match by mod prefix + "chest" in the name rather than hardcoding the full
-- list, so trapped/redstone variants are picked up automatically.
local function is_chest_node(name)
	if name:sub(1, 11) ~= "mcl_chests:" then return false end
	if name:find("ender", 1, true) then return false end -- per-player inv, skip
	return name:find("chest", 1, true) ~= nil
end

-- A stack is safe to merge only if it can actually stack (max > 1) and carries
-- no per-item state we'd destroy by rebuilding it (wear or metadata). Tools,
-- named items, damaged gear, etc. are therefore left exactly where they are.
local function is_mergeable(stack)
	if stack:is_empty() then return false end
	if stack:get_stack_max() <= 1 then return false end
	if stack:get_wear() ~= 0 then return false end
	local meta = stack:get_meta():to_table()
	if meta.fields and next(meta.fields) then return false end
	return true
end

-- Collect every chest within `radius` nodes of `pos`.
-- Returns a list of { pos = <node pos>, inv = <InvRef> }.
local function nearby_chests(pos, radius)
	local found = {}
	local cx, cy, cz = math.floor(pos.x), math.floor(pos.y), math.floor(pos.z)
	for x = cx - radius, cx + radius do
		for y = cy - radius, cy + radius do
			for z = cz - radius, cz + radius do
				local p = { x = x, y = y, z = z }
				if is_chest_node(core.get_node(p).name) then
					local inv = core.get_inventory({ type = "node", pos = p })
					if inv and inv:get_size("main") > 0 then
						found[#found + 1] = { pos = p, inv = inv }
					end
				end
			end
		end
	end
	return found
end

-- Take up to 16 of `name` out of the chest at `pos`, from the leftmost slot
-- holding it. Returns the taken ItemStack (empty if the item is gone now).
local function take_from_chest(pos, name)
	local inv = core.get_inventory({ type = "node", pos = pos })
	if not inv then return ItemStack("") end
	for idx, stack in ipairs(inv:get_list("main")) do
		if not stack:is_empty() and stack:get_name() == name then
			local take = math.min(16, stack:get_count())
			stack:set_count(stack:get_count() - take)
			inv:set_stack("main", idx, stack)
			local got = ItemStack(name)
			got:set_count(take)
			return got
		end
	end
	return ItemStack("")
end

-- Put as much of `stack` as fits into the chest at `pos`; returns the leftover
-- (empty if it all fit; the whole stack back if the chest node is gone).
local function put_in_chest(pos, stack)
	local inv = core.get_inventory({ type = "node", pos = pos })
	if not inv then return stack end
	return inv:add_item("main", stack)
end

-- Spill an itemstack onto the ground, so carried items are never destroyed.
local function drop_item(pos, stack)
	if stack and not stack:is_empty() then
		core.add_item({ x = pos.x, y = pos.y + 0.6, z = pos.z }, stack)
	end
end

----------------------------------------
-- B2a. Cosmetics: held item + chest lid
----------------------------------------

-- A tiny attached entity that draws the carried item in the golem's hand, the
-- way held items are shown. Created when the golem picks up, removed on drop.
core.register_entity("copper_golem:held", {
	initial_properties = {
		visual      = "wielditem",
		wield_item  = "",
		visual_size = { x = 0.3, y = 0.3, z = 0.3 }, -- tune: on-screen size of the item
		physical    = false,
		pointable   = false,
		collide_with_objects = false,
		static_save = false,
	},
	on_activate = function(self, staticdata)
		self._age = 0
		if staticdata and staticdata ~= "" then
			self.object:set_properties({ wield_item = staticdata })
		end
	end,
	-- Self-destruct if it ever loses its parent (golem unloaded/removed).
	on_step = function(self, dtime)
		self._age = self._age + dtime
		if self._age > 1 and not self.object:get_attach() then
			self.object:remove()
		end
	end,
})

-- Right-hand attachment for the held item. Offsets are in the golem model's own
-- units (1 px = 0.625 units); the arm_r hand sits ~6 units below the arm bone
-- pivot. TUNE in-game until the item sits nicely in the hand.
local HELD_BONE   = "arm_r"
local HELD_OFFSET = vector.new(0, -5.5, 1.5)
local HELD_ROT    = vector.new(0, 0, 0)

local function hide_held(self)
	if self._held_obj then
		if self._held_obj:get_luaentity() then self._held_obj:remove() end
		self._held_obj = nil
	end
end

local function show_held(self, itemname)
	hide_held(self)
	if not itemname or itemname == "" then return end
	local obj = core.add_entity(self.object:get_pos(), "copper_golem:held", itemname)
	if obj then
		obj:set_attach(self.object, HELD_BONE, HELD_OFFSET, HELD_ROT)
		self._held_obj = obj
	end
end

-- Mineclonia animates a chest via a separate lid entity ("mcl_chests:chest")
-- that tracks who has it open through :open(key)/:close(key). We drive it with a
-- key unique to this golem, so the lid opens/closes for the golem just like for a
-- player -- and won't slam shut on a player who also has it open. No-ops if the
-- lid entity isn't there (animated chests off, or not spawned yet).
local function chest_lid_entity(pos)
	for _, obj in ipairs(core.get_objects_inside_radius(pos, 1.5)) do
		local l = obj:get_luaentity()
		if l and l.name == "mcl_chests:chest" then return l end
	end
end

local function open_chest_lid(self, pos)
	local lid = chest_lid_entity(pos)
	if lid then lid:open(tostring(self.object)) end
	self._lid_pos = pos
	self._lid_age = 0
end

local function close_chest_lid(self)
	if not self._lid_pos then return end
	local lid = chest_lid_entity(self._lid_pos)
	if lid then lid:close(tostring(self.object)) end
	self._lid_pos = nil
end

-- Pick one sorting job: a mergeable stack sitting in a chest that is NOT its
-- "home" (the nearby chest already holding the most of that item), whose home
-- still has room. Carrying it toward the bigger pile gathers like with like
-- (BotW-style); since every move grows the largest pile it always converges,
-- so no memory of past chests is needed. Returns { src=<pos>, name=<item>,
-- dest=<pos> }, or nil when nothing is out of place.
local function plan_sort_job(pos)
	local chests = nearby_chests(pos, config.chest_radius)
	if #chests < 2 then return nil end           -- need a source and a separate home

	-- For each item type, find its home = the chest holding the most of it
	-- (ties broken by the earliest chest in scan order). Store the chest TABLE
	-- so we can compare it by reference below.
	local home = {} -- name -> { chest = <chest>, count = N }
	for _, chest in ipairs(chests) do
		local counts = {}
		for _, stack in ipairs(chest.inv:get_list("main")) do
			if is_mergeable(stack) then
				local n = stack:get_name()
				counts[n] = (counts[n] or 0) + stack:get_count()
			end
		end
		for name, n in pairs(counts) do
			if not home[name] or n > home[name].count then
				home[name] = { chest = chest, count = n }
			end
		end
	end

	-- The first stack that is away from its home AND whose home has room is the
	-- job. (If a home is full, that item just stays put -- natural overflow.)
	for _, chest in ipairs(chests) do
		for _, stack in ipairs(chest.inv:get_list("main")) do
			if is_mergeable(stack) then
				local h = home[stack:get_name()]
				if h.chest ~= chest
						and h.chest.inv:room_for_item("main", ItemStack(stack:get_name())) then
					return { src = chest.pos, name = stack:get_name(), dest = h.chest.pos }
				end
			end
		end
	end
	return nil
end

-- In-place tidy of a SINGLE chest (the original behaviour): merge each item's
-- partial stacks into the fewest stacks possible, reusing the slots it already
-- occupies (full stacks first, leftovers emptied). The courier handles moving
-- items between chests; this handles compacting them within one. Only writes a
-- slot when it actually changes (so it doesn't disturb an open chest formspec).
-- Returns true if anything changed.
local function compact_chest(inv)
	local list = inv:get_list("main")
	local total, slots_of = {}, {}
	for idx, stack in ipairs(list) do
		if is_mergeable(stack) then
			local n = stack:get_name()
			total[n] = (total[n] or 0) + stack:get_count()
			slots_of[n] = slots_of[n] or {}
			slots_of[n][#slots_of[n] + 1] = idx
		end
	end
	local changed = false
	for name, slots in pairs(slots_of) do
		local remaining = total[name]
		local maxn = ItemStack(name):get_stack_max()
		for _, idx in ipairs(slots) do
			local put = math.min(remaining, maxn)
			remaining = remaining - put
			local newstack = put > 0 and ItemStack(name .. " " .. put) or ItemStack("")
			if newstack:to_string() ~= list[idx]:to_string() then
				inv:set_stack("main", idx, newstack)
				changed = true
			end
		end
	end
	return changed
end

-- Tidy every chest within range; returns the positions that changed (for the
-- "working" particles). Used as the golem's fallback job when nothing needs
-- carrying between chests.
local function compact_nearby(pos)
	local changed = {}
	for _, c in ipairs(nearby_chests(pos, config.chest_radius)) do
		if compact_chest(c.inv) then changed[#changed + 1] = c.pos end
	end
	return changed
end

----------------------------------------
-- B3. Movement AI (simple self-contained state machine)
----------------------------------------
--
-- Four modes, no pathfinding, no mob framework -- just velocity + yaw +
-- animation swaps:
--   "idle"      stand still for a random pause
--   "walk"      stroll a random heading for a random burst
--   "to_source" head to the chest holding a misplaced stack (planned every
--               organize_cooldown seconds) and pick up <=16 of it
--   "to_dest"   carry that stack to its home chest and deposit it, with
--               particles over the chest; overflow/unreachable items are dropped
--
-- Fields on `self`:
--   _mode           : one of the four strings above
--   _mode_timer     : seconds left in the current mode
--   _job            : { src, name, dest } the current sort job
--   _carry          : ItemStack being carried from source to destination
--   _organize_cool  : seconds until the next sort trip
--   _anim           : animation currently playing (avoid pointless resets)

local function set_anim(self, name)
	if self._anim == name then return end -- don't restart a looping animation
	self._anim = name
	self.object:set_animation(ANIM[name], ANIM_SPEED, 0, true)
end

local function halt(self)
	local v = self.object:get_velocity()
	self.object:set_velocity({ x = 0, y = v.y, z = 0 })
end

-- Drive horizontal velocity along the current yaw every step, so wall
-- collisions (which zero a component) don't leave the golem drifting.
local function push_forward(self, speed)
	local yaw = self.object:get_yaw()
	local v   = self.object:get_velocity()
	self.object:set_velocity({
		x = -math.sin(yaw) * speed,
		y = v.y,
		z =  math.cos(yaw) * speed,
	})
end

-- Face a world position (yaw convention matches push_forward).
local function face_pos(self, target)
	local pos = self.object:get_pos()
	self.object:set_yaw(math.atan2(-(target.x - pos.x), target.z - pos.z))
end

local function start_walk(self)
	self._mode = "walk"
	self._mode_timer = math.random() * (config.walk_time_max - config.walk_time_min)
		+ config.walk_time_min
	self.object:set_yaw(math.random() * (2 * math.pi))
	set_anim(self, "walk")
end

-- Dumb obstacle avoidance: head for `target`, but if we stop making progress
-- (walked into a wall taller than the 1-block step) sidestep at an angle for a
-- moment, then resume. Cheap and good enough for short indoor chest hops.
local DETOUR_TRIGGER = 1.0          -- seconds of no progress before sidestepping
local DETOUR_TIME    = 0.7          -- seconds spent sidestepping
local DETOUR_ANGLE   = math.rad(75) -- how far to turn off course when stuck

local function travel_toward(self, target, speed_factor, dtime)
	if (self._detour_time or 0) > 0 then
		self._detour_time = self._detour_time - dtime
		self.object:set_yaw(self._detour_yaw)
	else
		face_pos(self, target)
		local pos   = self.object:get_pos()
		local moved = self._last_pos and vector.distance(pos, self._last_pos) or 1
		if moved < 0.04 then
			self._stuck_time = (self._stuck_time or 0) + dtime
			if self._stuck_time > DETOUR_TRIGGER then
				self._stuck_time  = 0
				local side = (math.random() < 0.5) and 1 or -1
				self._detour_yaw  = self.object:get_yaw() + side * DETOUR_ANGLE
				self._detour_time = DETOUR_TIME
			end
		else
			self._stuck_time = 0
		end
		self._last_pos = pos
	end
	push_forward(self, config.seek_speed * speed_factor)
end

-- Give-up fallback while carrying: tuck the item into a nearby chest (preferring
-- one that already holds it, to stay grouped) instead of littering the floor.
-- Only drops what genuinely won't fit anywhere in range.
local function stash_or_drop(self, pos)
	if not self._carry or self._carry:is_empty() then hide_held(self); return end
	local name   = self._carry:get_name()
	local chests = nearby_chests(pos, config.chest_radius)
	for _, c in ipairs(chests) do          -- first, chests already holding this item
		if c.inv:contains_item("main", ItemStack(name)) then
			self._carry = c.inv:add_item("main", self._carry)
			if self._carry:is_empty() then break end
		end
	end
	for _, c in ipairs(chests) do          -- then any chest with room
		if self._carry:is_empty() then break end
		self._carry = c.inv:add_item("main", self._carry)
	end
	drop_item(pos, self._carry)            -- whatever's left over
	self._carry = ItemStack("")
	hide_held(self)
end

local function start_idle(self)
	self._mode = "idle"
	self._mode_timer = math.random() * (config.idle_time_max - config.idle_time_min)
		+ config.idle_time_min
	close_chest_lid(self) -- safety: never wander off leaving a lid open
	self._detour_time = 0
	self._stuck_time  = 0
	halt(self)
	-- Occasionally glance around (head yaw clip) instead of standing dead still.
	set_anim(self, math.random() < 0.4 and "look" or "stand")
end

-- Copper sparkles over a chest the golem just sorted into.
local function work_particles(chest_pos)
	core.add_particlespawner({
		amount = 10, time = 0.6,
		minpos = vector.offset(chest_pos, -0.4, 0.55, -0.4),
		maxpos = vector.offset(chest_pos,  0.4, 0.9,  0.4),
		minvel = { x = -0.2, y = 0.3, z = -0.2 },
		maxvel = { x =  0.2, y = 0.8, z =  0.2 },
		minexptime = 0.4, maxexptime = 0.9,
		minsize = 0.8, maxsize = 1.6,
		texture = "mcl_copper_block.png",
	})
end

-- Burst when an axe scrapes a tier of oxidation (or the wax) off the golem.
local function scrape_particles(pos, texture)
	core.add_particlespawner({
		amount = 14, time = 0.3,
		minpos = vector.offset(pos, -0.3, 0.2, -0.3),
		maxpos = vector.offset(pos,  0.3, 1.2,  0.3),
		minvel = { x = -0.6, y = 0.4, z = -0.6 },
		maxvel = { x =  0.6, y = 1.0, z =  0.6 },
		minexptime = 0.3, maxexptime = 0.7,
		minsize = 0.7, maxsize = 1.4,
		texture = texture or "mcl_copper_block.png",
	})
end

-- A flourish of rising gold stars -- feedback for axe de-oxidation.
local function star_particles(pos)
	core.add_particlespawner({
		amount = 16, time = 0.3,
		minpos = vector.offset(pos, -0.3, 0.1, -0.3),
		maxpos = vector.offset(pos,  0.3, 1.2,  0.3),
		minvel = { x = -0.5, y = 0.6, z = -0.5 },
		maxvel = { x =  0.5, y = 1.4, z =  0.5 },
		minacc = { x = 0, y = -1, z = 0 }, maxacc = { x = 0, y = -2, z = 0 },
		minexptime = 0.5, maxexptime = 1.0,
		minsize = 0.7, maxsize = 1.6,
		texture = "copper_golem_star.png",
		glow = 14,
	})
end

-- Destroy the golem (killable like an iron golem): drop its loot + whatever it
-- was carrying, clean up its cosmetics, and remove it.
local DEATH_DROP_MIN, DEATH_DROP_MAX = 1, 3 -- copper ingots dropped on death
local function golem_die(self)
	local pos = self.object:get_pos()
	if pos then
		drop_item(pos, self._carry)        -- never swallow a carried item
		for _ = 1, math.random(DEATH_DROP_MIN, DEATH_DROP_MAX) do
			core.add_item(pos, "mcl_copper:copper_ingot")
		end
		scrape_particles(pos)              -- copper bursts apart
	end
	self._carry = ItemStack("")
	close_chest_lid(self)
	hide_held(self)
	self.object:remove()
end

-- Water interaction (step 4): the golem won't stroll off dry land INTO surface
-- water, but once submerged it just trudges along the bottom (gravity already
-- sinks it; no breath system, so it never drowns). Water contact also speeds up
-- oxidation -- unless waxed, which halts oxidation entirely.
local WATER_OXIDATION_MULT = 3.0   -- oxidation rate multiplier while in water

local function is_water_name(name)
	return core.get_item_group(name, "water") > 0
end

-- Standing in water? (feet node submerged)
local function in_water(self)
	local pos = self.object:get_pos()
	return pos ~= nil and is_water_name(core.get_node(
		{ x = pos.x, y = pos.y + 0.1, z = pos.z }).name)
end

-- Surface water directly ahead at foot level (along the current heading)?
local function water_ahead(self)
	local pos = self.object:get_pos()
	if not pos then return false end
	local yaw = self.object:get_yaw()
	return is_water_name(core.get_node({
		x = pos.x - math.sin(yaw) * 0.8,
		y = pos.y + 0.1,
		z = pos.z + math.cos(yaw) * 0.8,
	}).name)
end

-- Oxidation slows the golem down (Minecraft: 100% / 75% / 50% / frozen),
-- indexed by _stage 1..4. At the terminal stage the factor is 0: it seizes up.
local STAGE_SPEED = { 1.0, 0.75, 0.5, 0.0 }
local LIGHTNING_BOOST      = 2.0  -- speed multiplier during the post-lightning charge
local LIGHTNING_BOOST_TIME = 8    -- seconds the hyper-charge lasts

-- Per-step AI update.
local function update_movement(self, dtime)
	-- Watchdog: a chest lid is only meant to be held open for the brief dwell. If
	-- it has stayed open much longer, something went wrong -- force it shut. This
	-- is what guarantees a golem can never leave a chest stuck open.
	if self._lid_pos then
		self._lid_age = (self._lid_age or 0) + dtime
		if self._lid_age > config.chest_dwell + 2 then close_chest_lid(self) end
	end

	-- A fully oxidized golem is immobilized -- stand frozen and skip the AI.
	-- (Statue pose, dropping held items, and comparator output come in a later step.)
	local speed_factor = STAGE_SPEED[self._stage] or 1.0
	if speed_factor <= 0 then
		close_chest_lid(self) -- don't freeze mid-interaction leaving a lid open
		halt(self)
		set_anim(self, "stand")
		return
	end

	-- Temporary post-lightning hyper-charge.
	if (self._boost_timer or 0) > 0 then
		self._boost_timer = self._boost_timer - dtime
		speed_factor = speed_factor * LIGHTNING_BOOST
	end

	self._mode_timer    = (self._mode_timer or 0) - dtime
	self._organize_cool = (self._organize_cool or 0) - dtime

	local mode = self._mode or "idle"

	if mode == "idle" or mode == "walk" then
		-- Time for a sort trip? Plan one if something nearby is out of place.
		if self._organize_cool <= 0 then
			local pos = self.object:get_pos()
			local job = pos and plan_sort_job(pos)
			if job then
				self._job = job
				self._mode = "to_source"
				self._mode_timer = config.seek_timeout
				set_anim(self, "walk")
				return
			end
			-- Nothing to move between chests: tidy partial stacks WITHIN each one
			-- (the original in-place behaviour). If it tidied something, treat it as
			-- a full sort trip; otherwise re-check soon for new work.
			local tidied = pos and compact_nearby(pos) or {}
			for _, p in ipairs(tidied) do work_particles(p) end
			self._organize_cool = (#tidied > 0) and config.organize_cooldown or 4
		end
		if self._mode_timer <= 0 then
			if mode == "walk" then start_idle(self) else start_walk(self) end
		elseif mode == "walk" then
			-- Don't wander off dry land into surface water; turn away instead.
			-- (An already-submerged golem skips this and walks along the bottom.)
			if water_ahead(self) and not in_water(self) then
				self.object:set_yaw(self.object:get_yaw()
					+ math.pi * (0.5 + math.random()))
				halt(self)
			else
				push_forward(self, config.walk_speed * speed_factor)
			end
		end

	elseif mode == "to_source" then
		local pos = self.object:get_pos()
		local job = self._job
		-- Dwelling at the open chest: stand for a beat so the lid animation plays.
		if self._lid_pos then
			halt(self)
			self._chest_timer = (self._chest_timer or 0) - dtime
			if self._chest_timer <= 0 then
				close_chest_lid(self)
				if not self._carry or self._carry:is_empty() then
					self._job = nil
					self._organize_cool = 4
					start_idle(self)
				else
					self._mode = "to_dest"
					self._mode_timer = config.seek_timeout
					if job then face_pos(self, job.dest) end
					set_anim(self, "walk")
				end
			end
			return
		end
		-- Travelling to the chest holding the misplaced stack.
		if not pos or not job or not is_chest_node(core.get_node(job.src).name)
				or self._mode_timer <= 0 then
			self._job = nil
			self._organize_cool = 4
			start_idle(self)
			return
		end
		local dx, dz = job.src.x - pos.x, job.src.z - pos.z
		if dx * dx + dz * dz <= 1.6 * 1.6 then
			-- Arrived: open the lid, grab <=16, show it in hand, then dwell.
			open_chest_lid(self, job.src)
			self._carry = take_from_chest(job.src, job.name)
			if not self._carry:is_empty() then show_held(self, self._carry:get_name()) end
			self._chest_timer = config.chest_dwell
			halt(self)
			face_pos(self, job.src)
			set_anim(self, "stand")
		else
			face_pos(self, job.src)
			if water_ahead(self) and not in_water(self) then
				self._job = nil
				self._organize_cool = 4
				start_idle(self)
			else
				travel_toward(self, job.src, speed_factor, dtime)
			end
		end

	elseif mode == "to_dest" then
		local pos = self.object:get_pos()
		local job = self._job
		-- Dwelling at the open home chest after depositing.
		if self._lid_pos then
			halt(self)
			self._chest_timer = (self._chest_timer or 0) - dtime
			if self._chest_timer <= 0 then
				close_chest_lid(self)
				self._job = nil
				self._organize_cool = config.organize_cooldown
				start_idle(self)
			end
			return
		end
		-- Carry the stack to its home chest. Anything that won't fit or can't be
		-- reached is dropped so a carried item is never lost.
		if not pos or not self._carry or self._carry:is_empty() then
			hide_held(self)
			self._job = nil
			start_idle(self)
			return
		end
		if not job or not is_chest_node(core.get_node(job.dest).name)
				or self._mode_timer <= 0 then
			stash_or_drop(self, pos)        -- couldn't reach home: tuck it away, don't litter
			self._job = nil
			self._organize_cool = 4
			start_idle(self)
			return
		end
		local dx, dz = job.dest.x - pos.x, job.dest.z - pos.z
		if dx * dx + dz * dz <= 1.6 * 1.6 then
			-- Arrived: open the lid, deposit (spill overflow), drop the held item,
			-- and tidy the home chest's stacks while we're here.
			open_chest_lid(self, job.dest)
			drop_item(pos, put_in_chest(job.dest, self._carry))
			local dinv = core.get_inventory({ type = "node", pos = job.dest })
			if dinv then compact_chest(dinv) end
			self._carry = ItemStack("")
			hide_held(self)
			work_particles(job.dest)
			self._chest_timer = config.chest_dwell
			halt(self)
			face_pos(self, job.dest)
			set_anim(self, "stand")
		else
			face_pos(self, job.dest)
			if water_ahead(self) and not in_water(self) then
				stash_or_drop(self, pos)    -- water in the way: tuck it away, don't litter
				self._job = nil
				self._organize_cool = 4
				start_idle(self)
			else
				travel_toward(self, job.dest, speed_factor, dtime)
			end
		end
	end
end

--------------------------------------------------------------------------------
-- ENTITY  --  the thin glue between (A) and (B). Holds no heavy logic itself.
--------------------------------------------------------------------------------

local GRAVITY = { x = 0, y = -9.81, z = 0 }

local golem_def = {
	initial_properties = (function()
		local p = base_visual_properties()
		p.textures = mesh_textures(1) -- start un-oxidised; updated on activate
		return p
	end)(),

	-- Persistent fields (saved via get_staticdata):
	_stage      = 1,   -- current oxidation stage 1..4
	_age        = 0,   -- accumulated real seconds, drives oxidation
	_waxed      = false,-- true halts oxidation (honeycomb)
	_creator    = nil, -- player name who built it (cosmetic)
	_carry      = nil, -- ItemStack carried between chests (persisted, see staticdata)
	-- Transient (movement state machine, see B3):
	_mode          = "idle",
	_mode_timer    = 0,
	_job           = nil, -- { src=<pos>, name=<item>, dest=<pos> } the current sort job
	_organize_cool = 0,
	_anim          = nil,
	_boost_timer   = 0,   -- seconds of post-lightning hyper-charge remaining
	_held_obj      = nil, -- attached entity showing the carried item in hand
	_lid_pos       = nil, -- chest pos whose lid this golem currently holds open
	_chest_timer   = 0,   -- seconds left dwelling at an open chest

	on_activate = function(self, staticdata, dtime_s)
		-- Restore saved state. staticdata is a serialised table; on first spawn
		-- it carries the starting stage chosen from the copper block used.
		local data = staticdata ~= "" and core.deserialize(staticdata) or nil
		if type(data) == "table" then
			self._stage   = data.stage   or 1
			self._age     = data.age     or 0
			self._waxed   = data.waxed   or false
			self._creator = data.creator
			self._carry   = ItemStack(data.carry or "")
		end

		-- Falls under gravity and rests on the ground (engine handles node
		-- collision), but takes NO fall damage -- like an iron/snow golem: the
		-- engine never fall-damages a luaentity, and HP is only ever subtracted in
		-- on_punch. Re-assert the damage groups here so even a golem spawned before
		-- HP existed becomes killable on reload.
		self.object:set_acceleration(GRAVITY)
		self.object:set_armor_groups({ fleshy = 100 })
		apply_stage_visuals(self.object, self._stage)

		-- If it was mid-carry when unloaded, return the item to the world so
		-- nothing is lost; it'll plan a fresh sort job from idle. The held-item
		-- and lid states are transient cosmetics, reset clean on every load.
		local here = self.object:get_pos()
		if here and self._carry and not self._carry:is_empty() then
			drop_item(here, self._carry)
		end
		self._carry    = ItemStack("")
		self._held_obj = nil
		self._lid_pos  = nil
		self._chest_timer = 0

		-- Start out standing; the AI state machine takes over from here.
		-- First sort trip comes a few seconds after activation.
		self.object:set_animation(ANIM.stand, ANIM_SPEED, 0, true)
		self._anim          = "stand"
		self._mode          = "idle"
		self._job           = nil
		self._mode_timer    = 0
		self._organize_cool = 3
	end,

	-- On removal/unload, let go of any chest lid and clean up the held item, so
	-- nothing is left animated open and no orphan item entity lingers.
	on_deactivate = function(self)
		close_chest_lid(self)
		hide_held(self)
	end,

	get_staticdata = function(self)
		return core.serialize({
			stage   = self._stage,
			age     = self._age,
			waxed   = self._waxed,
			creator = self._creator,
			carry   = (self._carry and self._carry:to_string()) or "",
		})
	end,

	on_step = function(self, dtime)
		-- (B3) Movement AI; chest sorting (B2) runs from its to_source/to_dest states.
		update_movement(self, dtime)

		-- (B1) Oxidation -------------------------------------------------------
		if not self._waxed and self._stage < NUM_STAGES then
			-- Water contact accelerates oxidation (waxed golems skip this block).
			local rate = in_water(self) and WATER_OXIDATION_MULT or 1.0
			self._age = self._age + dtime * rate
			local want = stage_for_age(self._age)
			if want > self._stage then
				self._stage = want
				apply_stage_visuals(self.object, self._stage)
			end
		end
	end,

	-- Right-click interactions (neither deals damage):
	--   * Axe       -> scrape one oxidation tier (wax first), Minecraft's "strip
	--                  with an axe" gesture; a sparkle of stars marks it.
	--   * Honeycomb -> wax the golem to permanently halt oxidation.
	on_rightclick = function(self, clicker)
		if not clicker or not clicker:is_player() then return end
		local wield = clicker:get_wielded_item()
		local pos   = self.object:get_pos()

		-- Axe: de-oxidize one step per right-click.
		if core.get_item_group(wield:get_name(), "axe") > 0 then
			local scraped = false
			if self._waxed then
				self._waxed = false               -- strip the wax first
				scraped = true
			elseif self._stage > 1 then
				self._stage = self._stage - 1
				-- Re-base the oxidation clock to this tier's start, or on_step's
				-- stage_for_age() would just re-oxidize it on the next tick.
				self._age = (self._stage - 1) * config.seconds_per_stage
				apply_stage_visuals(self.object, self._stage)
				scraped = true
			end
			if scraped then
				if pos then star_particles(pos) end
				-- Spend one use of axe durability (skipped in creative).
				local name = clicker:get_player_name()
				if not (core.is_creative_enabled and core.is_creative_enabled(name)) then
					if mcl_util and mcl_util.use_item_durability then
						mcl_util.use_item_durability(wield, 1)
					else
						wield:add_wear_by_uses(200)
					end
					clicker:set_wielded_item(wield)
				end
			end
			return
		end

		-- Honeycomb: wax to permanently stop oxidation (harmless if mcl_honey absent).
		if wield:get_name() == "mcl_honey:honeycomb" and not self._waxed then
			self._waxed = true
			local creative = core.is_creative_enabled
				and core.is_creative_enabled(clicker:get_player_name())
			if not creative then
				wield:take_item(1)
				clicker:set_wielded_item(wield)
			end
			if pos then
				core.add_particlespawner({
					amount = 16, time = 0.4,
					minpos = vector.offset(pos, -0.3, -0.3, -0.3),
					maxpos = vector.offset(pos,  0.3,  0.3,  0.3),
					minvel = { x = -0.3, y = 0.2, z = -0.3 },
					maxvel = { x =  0.3, y = 0.6, z =  0.3 },
					minexptime = 0.5, maxexptime = 1.0,
					minsize = 1, maxsize = 2,
					texture = "mcl_honey_honeycomb.png",
				})
			end
		end
	end,

	-- Punch handling: the golem is killable like an iron golem. Every hit deals its
	-- weapon's damage and dies at 0 HP (see golem_die). De-oxidation is NOT done
	-- here -- right-click with an axe for that (on_rightclick). No hurt particles
	-- (the copper sparkle is reserved for the golem's chest work). Fall damage stays
	-- excluded: the engine never fall-damages a luaentity and HP only drops here.
	on_punch = function(self, puncher, _tflp, _caps, _dir, damage)
		local pos = self.object:get_pos()
		if pos and puncher and puncher:get_pos() then -- a little knockback
			self.object:add_velocity(
				vector.multiply(vector.direction(puncher:get_pos(), pos), 3))
		end
		local hp = self.object:get_hp() - (damage or 0)
		if hp <= 0 then
			golem_die(self)
		else
			self.object:set_hp(hp)
		end
		return true
	end,

	-- Lightning purges ALL oxidation back to pristine and briefly hyper-charges
	-- the golem (Minecraft "atmospheric restoration"). Returning true skips the
	-- default lightning damage. mcl_lightning calls this for any luaentity within
	-- ~3.5 nodes of a strike. Wax (if any) is left intact, so it re-locks at clean.
	_on_lightning_strike = function(self, _pos, _pos2, _objects)
		self._stage = 1
		self._age   = 0
		apply_stage_visuals(self.object, 1)
		self._boost_timer = LIGHTNING_BOOST_TIME
		local p = self.object:get_pos()
		if p then scrape_particles(p) end
		return true
	end,
}

core.register_entity("copper_golem:golem", golem_def)

--------------------------------------------------------------------------------
-- SPAWN TRIGGER  --  carved pumpkin on a copper block builds the golem
--------------------------------------------------------------------------------
--
-- The golem starts oxidised to MATCH the copper block it was built from
-- (build one from weathered copper -> it spawns weathered). Irreversible, so it
-- continues from there. This map turns a node name into a starting stage.
local COPPER_BLOCK_STAGE = {
	["mcl_copper:block"]           = 1,
	["mcl_copper:block_exposed"]   = 2,
	["mcl_copper:block_weathered"] = 3,
	["mcl_copper:block_oxidized"]  = 4,
}

-- Particles when a golem is built, mirroring the snow/iron golem feel.
local function spawn_particles(pos)
	core.add_particlespawner({
		amount = 24, time = 0.5,
		minpos = vector.offset(pos, -0.4, -0.4, -0.4),
		maxpos = vector.offset(pos,  0.4,  0.4,  0.4),
		minvel = { x = -0.5, y = 0.3, z = -0.5 },
		maxvel = { x =  0.5, y = 1.0, z =  0.5 },
		minacc = { x = 0, y = -1, z = 0 }, maxacc = { x = 0, y = -2, z = 0 },
		minexptime = 0.6, maxexptime = 1.2,
		minsize = 1, maxsize = 3,
		texture = "copper_golem.png",
	})
end

-- Called after a carved pumpkin is placed at `pos`. If a copper block sits
-- directly below, consume both nodes and summon a golem in their place.
function copper_golem.check_summon(pos, placer)
	-- The pumpkin may already have been consumed by the iron/snow golem check
	-- that runs before us, so confirm it's still there.
	if core.get_node(pos).name ~= "mcl_farming:pumpkin_face" then return end

	local below      = { x = pos.x, y = pos.y - 1, z = pos.z }
	local below_name = core.get_node(below).name
	local start_stage = COPPER_BLOCK_STAGE[below_name]
	if not start_stage then return end -- not a (non-waxed) copper block

	-- Remove the two build nodes and settle anything resting on them.
	core.remove_node(pos)
	core.remove_node(below)
	core.check_for_falling(pos)
	core.check_for_falling(below)

	-- Spawn slightly above the copper block's old position so it drops in.
	local spawn_pos = { x = below.x, y = below.y + 0.5, z = below.z }
	local staticdata = core.serialize({
		stage   = start_stage,
		age     = (start_stage - 1) * config.seconds_per_stage, -- consistent age
		waxed   = false,
		creator = placer and placer:is_player() and placer:get_player_name() or nil,
	})
	local obj = core.add_entity(spawn_pos, "copper_golem:golem", staticdata)
	if obj then
		spawn_particles(spawn_pos)
	end
end

-- Wire ourselves into the carved pumpkin WITHOUT editing the base game: save the
-- pumpkin's existing after_place_node (which handles iron/snow golems) and chain
-- our check after it via core.override_item. mcl_farming is a hard dependency, so
-- the node is guaranteed to exist by the time this runs.
do
	local pumpkin = core.registered_nodes["mcl_farming:pumpkin_face"]
	if pumpkin then
		local original = pumpkin.after_place_node
		core.override_item("mcl_farming:pumpkin_face", {
			after_place_node = function(pos, placer, itemstack, pointed_thing)
				if original then
					original(pos, placer, itemstack, pointed_thing)
				end
				copper_golem.check_summon(pos, placer)
			end,
		})
	else
		core.log("warning",
			"[copper_golem] mcl_farming:pumpkin_face not found; " ..
			"build-to-spawn disabled. Is mcl_farming installed?")
	end
end

core.log("action", "[copper_golem] loaded")
